// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpgafdbmmdazcihzooie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwZ2FmZGJtbWRhemNpaHpvb2llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjM1MTQsImV4cCI6MjA2Nzc5OTUxNH0.ZUR8nL_ehn4oKud4085Ik4kvOfwOc2S87jNKXvT1_7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});